#!/usr/bin/env python3
"""Reproduce the common X11 color table from archived, pinned Ghostty data. Offline."""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "kinetica-terminal/third-party/x11-rgb.txt"
data = SOURCE.read_bytes()
assert hashlib.sha256(data).hexdigest() == "f8e3a7bea17acc0b91e6285c5d32001db27d84c4461c655afdbce9dbeb4fb6f0"
colors = {}
for line in data.decode().splitlines():
    r, g, b, name = line.split(maxsplit=3)
    key = name.lower()
    color = int(r) << 16 | int(g) << 8 | int(b)
    assert key not in colors or colors[key] == color
    colors[key] = color
table = "\n".join(f"{color:06x} {name}" for name, color in sorted(colors.items()))
target = ROOT / "kinetica-terminal/src/generated/TerminalX11Colors.kt"
target.write_text('''// Generated by scripts/generate-terminal-x11-colors.py. Do not hand-edit.
// X11 rgb.txt from Ghostty 4da7523faba68ccb4042ea20585817098a51c015.
// Copyright 1985, 1989, 1998 The Open Group. See third-party/X11-RGB-LICENSE.txt.
// Source SHA-256: ''' + hashlib.sha256(data).hexdigest() + '''
package io.heapy.kinetica.terminal

internal fun terminalX11Color(name: String): Int? =
    if (name.any { it.code > 127 }) null else terminalX11Colors[name.lowercase()]

private val terminalX11Colors: Map<String, Int> by lazy {
    """''' + table + '''""".lineSequence().associate { it.substring(7) to it.substring(0, 6).toInt(16) }
}
''')
print(f"Generated {len(colors)} X11 color names")
